### ISSUE TITLE
Crash and not responding (VSIX only)

### ISSUE THREAD

**Issue by grandoth** [JocysCom/VsAiCompanion#12]
**Environment**
Windows 11 22H2
Visual Studio 2022 (tried 17.10.1)
VS AI Companion 1.11.12.0 (Extension)

Both VS AI Companion and Visual studio become "Not Responding" and then crash when trying to submit a prompt.

However, if I run the application variant (.exe), it seems to work just fine. I have tried installing and reinstalling. Note: I had some trouble where uninstalling the vsix would only result in it being disabled. I manually removed the extension files, and seemed to be able to get a clean VSIX install, but still crashing.

Note: I would go back and try 1.10.41.0, but I used Extension Manager, and cannot figure out how to downgrade. I also don't see in marketplace where I can grab old version.

**Comment by EJocys** [comment]
@grandoth 

Thanks for reporting the issue. Released a new version with a couple of crash fixes. The extension should now show an error message before crashing, which should help pinpoint the issue if it continues to crash. Also, from now on, the extension file (*.vsix) will be included in the release downloads, making it easy to downgrade if needed.

2024-07-11 v1.11.20

- Fix: The app crashes if there are no video input devices.
- Fix: Crash on start in Visual Studio 2022 17.10.2.
- New: Crash message when crashing in Visual Studio.
- New: Developer option for the error panel.
- New: Option to log HTTP messages.
- New: AI function to get the current date, OS version, architecture, locale, and time zone.

https://github.com/JocysCom/VsAiCompanion/releases

**Comment by grandoth** [comment]
Thanks for the updates. I'm running 1.11.21 and finding the same behavior. I don't see an error message pop up in a separate dialog. I did enable the Error tab in developer options and HTTP logging. I can't click on the Error tab after clicking "Send Message" as the dialog is immediately unresponsive and goes "Not Responding" (along with Visual Studio).

Perhaps an important distinction:
In the vsix, when I press the "Enter" key, or click the blue "Send Message" button to send at chat message, visually, the button only takes focus (focus rectangle), but it does not "press" or change state.

In the app variant, when I press the "Enter" key, or click the blue "Send Message" button to send at chat message, visually, the button takes focus (focus rectangle), but also it does "press" ("Send Message" becomes disabled and "AnimationAndMediaStopRequest" becomes enabled).

Also, I am getting HttpClientLog_20240612.svclog showing up in the AppData Logs folder. However, it is only updating in when clicking "Send Message" in the App version. It seems like the vsix variant is going "Not Responding" before making http calls.

Other info:
I tried both running Visual Studio as a standard use and as Administrator with no difference in behavior.

**Comment by grandoth** [comment]
Closing this for now as it seems to be an issue with Visual Studio itself, based on an upgrade from 17.10.1 to 17.10.2 causing the issues to go away.

**Comment by grandoth** [comment]
Just kidding. It's still happening, just worked the first time? I'm not sure, the log doesn't show it.

**Comment by EJocys** [comment]
@grandoth Thanks for the additional information. I fixed another crash where the second instance of the app (let's say the first is running as a standalone app and the second is running in Visual Studio) would crash when sending a message while HTTP logging is enabled because the second instance is trying to write to the same log file, which is locked. The log file now has the process ID in its name. For example: `HttpClientLog_P7332_20240612.svclog`, so each process has its own log file. A new version is available to download in the marketplace:

2024-06-12 v1.11.23

- Fix: App crashes when trying to log into the same file.
- Update: Improve the loading process in Visual Studio.

https://github.com/JocysCom/VsAiCompanion/releases

**Comment by EJocys** [comment]
@grandoth If the crash still happens, I'll add an option to write the exception instantly to a file. That should help easily capture data on the most elusive exceptions.

**Comment by grandoth** [comment]
I finally had a chance to experiment a little bit more with this. I was still getting crashes, but I may have isolated the cause:

Findings:
- VSIX version does not seems to log to C:\Users\<user>\AppData\Roaming\Jocys.com\VS AI Companion\Logs despite the option to log being enabled.
- I used app "Everything" to look for a similarly named file elsewhere on my filesystem and didn't find one even in the cases where VSIX did inference without error.
- I think this is a repeatable scenario:
  - Start Visual Studio.
  - Open VS AI Companion extension.
  - Start debugging (note VS AI Companion window disappears).
  - Run VS AI Companion again.
  - Stop debugging (note VS AI Companion instance from debugging disappears and design-time instance reappears)
  - Exit Visual Studio.
  - Start Visual Studio with the same project.
  - VS AI Companion auto starts.
  - Do a chat inference (results in Not Responding and app close).

- I was able to get it working again by not having VS AI Companion enabled while debugging:
  - Start Visual Studio.
  - Start debugging.
  - Close VS AI Companion debugging instance.
  - Stop debugging.
  - Exit Visual Studio.
  - Start Visual Studio with the same project.
  - Chat inference works.
  - Note: If I didn't restart Visual Studio after closing the VS AI Companion debugging instance, it still exhibited the Not Responding/crash behavior.
- I was able to repeat this a few times.

**Comment by EJocys** [comment]
@grandoth Thanks for doing more testing and providing steps to replicate the issue. Unfortunately, I was unable to make it not respond or crash. I will keep this issue open in case I stumble onto this issue later.

**Comment by grandoth** [comment]
I have had one more crash on attempting send a prompt. I don't think it was based on the scenario I described above as I've been trying to avoid it :). However, in the moment I didn't think to review logs so the data point is of limited value. Just an update that I'm watching for it.

**Comment by EJocys** [comment]
Released multiple versions with crash fixes, so closing it for now.
